/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author joser
 */
public class frmBienvenido extends javax.swing.JFrame {

    /**
     * Creates new form frmBienvenido
     */
    int xMouse, yMouse;
    public frmBienvenido() {
        initComponents();
        this.setLocationRelativeTo(null);
        image();
    }

    public void image(){
     ImageIcon iconLogo = new ImageIcon(getClass().getResource("/img/Mundo.png"));
        Image fotoLogo = iconLogo.getImage().getScaledInstance(lblMundo.getWidth(), lblMundo.getHeight(), 0);
        lblMundo.setIcon(new ImageIcon(fotoLogo));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMundo = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JPanel();
        lblAcepto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlArrastrable = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMundo.setText("Mundo");
        jPanel1.add(lblMundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 100));

        btnAceptar.setBackground(new java.awt.Color(82, 120, 206));
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblAcepto.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        lblAcepto.setForeground(new java.awt.Color(255, 255, 255));
        lblAcepto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAcepto.setText("Entrar");
        lblAcepto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAcepto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAceptoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAceptoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAceptoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAceptarLayout = new javax.swing.GroupLayout(btnAceptar);
        btnAceptar.setLayout(btnAceptarLayout);
        btnAceptarLayout.setHorizontalGroup(
            btnAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAceptarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAceptarLayout.setVerticalGroup(
            btnAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAceptarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 110, 20));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Bienvenido a Fakebuk!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        pnlArrastrable.setBackground(new java.awt.Color(244, 244, 244));
        pnlArrastrable.setOpaque(false);
        pnlArrastrable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlArrastrableMouseDragged(evt);
            }
        });
        pnlArrastrable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlArrastrableMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlArrastrableLayout = new javax.swing.GroupLayout(pnlArrastrable);
        pnlArrastrable.setLayout(pnlArrastrableLayout);
        pnlArrastrableLayout.setHorizontalGroup(
            pnlArrastrableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        pnlArrastrableLayout.setVerticalGroup(
            pnlArrastrableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(pnlArrastrable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAceptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAceptoMouseClicked
        frmPrincipal iniciar = new frmPrincipal();
        this.dispose();
        iniciar.setVisible(true);
        
    }//GEN-LAST:event_lblAceptoMouseClicked

    private void lblAceptoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAceptoMouseEntered
        btnAceptar.setBackground(new Color(62,143,80));
    }//GEN-LAST:event_lblAceptoMouseEntered

    private void lblAceptoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAceptoMouseExited
        btnAceptar.setBackground(new Color(82,120,206));
    }//GEN-LAST:event_lblAceptoMouseExited

    private void pnlArrastrableMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlArrastrableMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_pnlArrastrableMouseDragged

    private void pnlArrastrableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlArrastrableMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlArrastrableMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBienvenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAcepto;
    private javax.swing.JLabel lblMundo;
    private javax.swing.JPanel pnlArrastrable;
    // End of variables declaration//GEN-END:variables
}
