/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author joser
 */
public class frmMural extends javax.swing.JPanel {

    /**
     * Creates new form frmMural
     */
    public frmMural() {
        initComponents();
        setSize(1000, 3300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUltimasPublicaciones = new javax.swing.JLabel();
        Muro4 = new javax.swing.JPanel();
        FotoPerfil4 = new javax.swing.JLabel();
        lblNombre4 = new javax.swing.JLabel();
        Panel4 = new javax.swing.JPanel();
        lblPublicacion4 = new javax.swing.JLabel();
        Muro1 = new javax.swing.JPanel();
        FotoPerfil1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        lblPublicacion1 = new javax.swing.JLabel();
        Muro2 = new javax.swing.JPanel();
        FotoPerfil2 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        lblPublicacion2 = new javax.swing.JLabel();
        Muro3 = new javax.swing.JPanel();
        FotoPerfil3 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        Panel3 = new javax.swing.JPanel();
        lblPublicacion3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUltimasPublicaciones.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblUltimasPublicaciones.setText("Ultimas publicaciones:");
        add(lblUltimasPublicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        Muro4.setBackground(new java.awt.Color(224, 224, 224));

        FotoPerfil4.setText("Foto perfil");
        FotoPerfil4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNombre4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblNombre4.setText("*Nombre*");

        lblPublicacion4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblPublicacion4.setText("*Publicacion de esta persona*");

        javax.swing.GroupLayout Panel4Layout = new javax.swing.GroupLayout(Panel4);
        Panel4.setLayout(Panel4Layout);
        Panel4Layout.setHorizontalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPublicacion4)
                .addContainerGap(507, Short.MAX_VALUE))
        );
        Panel4Layout.setVerticalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPublicacion4)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Muro4Layout = new javax.swing.GroupLayout(Muro4);
        Muro4.setLayout(Muro4Layout);
        Muro4Layout.setHorizontalGroup(
            Muro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Muro4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Muro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Muro4Layout.createSequentialGroup()
                        .addComponent(FotoPerfil4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre4)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Muro4Layout.setVerticalGroup(
            Muro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Muro4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Muro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre4)
                    .addComponent(FotoPerfil4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(Panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(Muro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1030, -1, -1));

        Muro1.setBackground(new java.awt.Color(224, 224, 224));

        FotoPerfil1.setText("Foto perfil");
        FotoPerfil1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNombre1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblNombre1.setText("*Nombre*");

        lblPublicacion1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblPublicacion1.setText("*Publicacion de esta persona*");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPublicacion1)
                .addContainerGap(507, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPublicacion1)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Muro1Layout = new javax.swing.GroupLayout(Muro1);
        Muro1.setLayout(Muro1Layout);
        Muro1Layout.setHorizontalGroup(
            Muro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Muro1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Muro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Muro1Layout.createSequentialGroup()
                        .addComponent(FotoPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Muro1Layout.setVerticalGroup(
            Muro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Muro1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Muro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre1)
                    .addComponent(FotoPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(Muro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        Muro2.setBackground(new java.awt.Color(224, 224, 224));

        FotoPerfil2.setText("Foto perfil");
        FotoPerfil2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNombre2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblNombre2.setText("*Nombre*");

        lblPublicacion2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblPublicacion2.setText("*Publicacion de esta persona*");

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPublicacion2)
                .addContainerGap(507, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPublicacion2)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Muro2Layout = new javax.swing.GroupLayout(Muro2);
        Muro2.setLayout(Muro2Layout);
        Muro2Layout.setHorizontalGroup(
            Muro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Muro2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Muro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Muro2Layout.createSequentialGroup()
                        .addComponent(FotoPerfil2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre2)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Muro2Layout.setVerticalGroup(
            Muro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Muro2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Muro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre2)
                    .addComponent(FotoPerfil2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(Muro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        Muro3.setBackground(new java.awt.Color(224, 224, 224));

        FotoPerfil3.setText("Foto perfil");
        FotoPerfil3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNombre3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblNombre3.setText("*Nombre*");

        lblPublicacion3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblPublicacion3.setText("*Publicacion de esta persona*");

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPublicacion3)
                .addContainerGap(507, Short.MAX_VALUE))
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPublicacion3)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Muro3Layout = new javax.swing.GroupLayout(Muro3);
        Muro3.setLayout(Muro3Layout);
        Muro3Layout.setHorizontalGroup(
            Muro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Muro3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Muro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Muro3Layout.createSequentialGroup()
                        .addComponent(FotoPerfil3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre3)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Muro3Layout.setVerticalGroup(
            Muro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Muro3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Muro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre3)
                    .addComponent(FotoPerfil3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(Muro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 700, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FotoPerfil1;
    private javax.swing.JLabel FotoPerfil2;
    private javax.swing.JLabel FotoPerfil3;
    private javax.swing.JLabel FotoPerfil4;
    private javax.swing.JPanel Muro1;
    private javax.swing.JPanel Muro2;
    private javax.swing.JPanel Muro3;
    private javax.swing.JPanel Muro4;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel4;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblNombre4;
    private javax.swing.JLabel lblPublicacion1;
    private javax.swing.JLabel lblPublicacion2;
    private javax.swing.JLabel lblPublicacion3;
    private javax.swing.JLabel lblPublicacion4;
    private javax.swing.JLabel lblUltimasPublicaciones;
    // End of variables declaration//GEN-END:variables
}
