/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author joser
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    
    int xMouse, yMouse;
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
         Image icon = new ImageIcon(getClass().getResource("/img/soloLogo.png")).getImage();
       this.setIconImage(icon); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Close = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tamaño = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Barra = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JPanel();
        Lupa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PerfilUsuario = new javax.swing.JPanel();
        Separador = new javax.swing.JLabel();
        lblFotoPerfil = new javax.swing.JLabel();
        Recomendados = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ScrollPane = new javax.swing.JScrollPane();
        PanelCrearPublicacion = new javax.swing.JPanel();
        EnQueEstasPensando = new javax.swing.JLabel();
        btnPublicar = new Clases.PanelRound();
        btnEntrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1046, 609));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setBackground(new java.awt.Color(82, 120, 206));
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CloseMouseReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");

        javax.swing.GroupLayout CloseLayout = new javax.swing.GroupLayout(Close);
        Close.setLayout(CloseLayout);
        CloseLayout.setHorizontalGroup(
            CloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CloseLayout.setVerticalGroup(
            CloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CloseLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        bg.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 30, 30));

        Tamaño.setBackground(new java.awt.Color(82, 120, 206));
        Tamaño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TamañoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TamañoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TamañoMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("_");

        javax.swing.GroupLayout TamañoLayout = new javax.swing.GroupLayout(Tamaño);
        Tamaño.setLayout(TamañoLayout);
        TamañoLayout.setHorizontalGroup(
            TamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TamañoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
        );
        TamañoLayout.setVerticalGroup(
            TamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TamañoLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        bg.add(Tamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 30, 30));

        btnActualizar.setBackground(new java.awt.Color(82, 120, 206));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N

        javax.swing.GroupLayout btnActualizarLayout = new javax.swing.GroupLayout(btnActualizar);
        btnActualizar.setLayout(btnActualizarLayout);
        btnActualizarLayout.setHorizontalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        btnActualizarLayout.setVerticalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnActualizarLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 30, 30));

        Barra.setBackground(new java.awt.Color(82, 120, 206));
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });
        Barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chiquito.png"))); // NOI18N
        Barra.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 39));

        txtBuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscar.setText("Buscar");
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarMousePressed(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        Barra.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 0, 236, 30));

        btnBuscar.setBackground(new java.awt.Color(82, 120, 206));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        Lupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa (1).png"))); // NOI18N

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addComponent(Lupa)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(Lupa))
        );

        Barra.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 0, 30, 28));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoBarra.png"))); // NOI18N
        Barra.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 140, -1));

        bg.add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 30));

        Separador.setText("________________________________________________");

        lblFotoPerfil.setText("Foto perfil");
        lblFotoPerfil.setToolTipText("");
        lblFotoPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PerfilUsuarioLayout = new javax.swing.GroupLayout(PerfilUsuario);
        PerfilUsuario.setLayout(PerfilUsuarioLayout);
        PerfilUsuarioLayout.setHorizontalGroup(
            PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerfilUsuarioLayout.createSequentialGroup()
                .addComponent(Separador)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(PerfilUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PerfilUsuarioLayout.setVerticalGroup(
            PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerfilUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(Separador))
        );

        bg.add(PerfilUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 290, 360));

        Recomendados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Amigos:");
        Recomendados.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 11, 129, -1));

        jLabel7.setText("Foto perfil");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Recomendados.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 129, 70, 70));

        jLabel8.setText("Foto perfil");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Recomendados.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 41, 70, 70));

        jLabel9.setText("Foto perfil");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Recomendados.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 217, 70, 70));

        jLabel10.setText("Foto perfil");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Recomendados.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 305, 70, 70));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Recomendados.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 240, 70));

        bg.add(Recomendados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 290, 380));

        ScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        bg.add(ScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 940, 700));

        PanelCrearPublicacion.setBackground(new java.awt.Color(255, 255, 255));
        PanelCrearPublicacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EnQueEstasPensando.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        EnQueEstasPensando.setText("¿En que estas pensando?");
        PanelCrearPublicacion.add(EnQueEstasPensando, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 12, -1, -1));

        btnPublicar.setBackground(new java.awt.Color(82, 120, 206));
        btnPublicar.setRoundBottomLeft(15);
        btnPublicar.setRoundBottomRight(15);
        btnPublicar.setRoundTopLeft(15);
        btnPublicar.setRoundTopRight(15);
        btnPublicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPublicarMouseClicked(evt);
            }
        });
        btnPublicar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrar.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEntrar.setText("Publicar");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntrarMouseExited(evt);
            }
        });
        btnPublicar.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 20));

        PanelCrearPublicacion.add(btnPublicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 110, 20));

        bg.add(PanelCrearPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 940, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BarraMousePressed

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y- yMouse);
    }//GEN-LAST:event_BarraMouseDragged

    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        Close.setBackground(new Color(255, 51, 0));
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        Close.setBackground(new Color(82,120,206));
    }//GEN-LAST:event_CloseMouseExited

    private void CloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseReleased
        
    }//GEN-LAST:event_CloseMouseReleased

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void TamañoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TamañoMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_TamañoMouseClicked

    private void TamañoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TamañoMouseEntered
        Tamaño.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_TamañoMouseEntered

    private void TamañoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TamañoMouseExited
        Tamaño.setBackground(new Color(82,120,206));
    }//GEN-LAST:event_TamañoMouseExited

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMousePressed
        if (txtBuscar.getText().equals("Buscar")) {
            txtBuscar.setText("");
        txtBuscar.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_txtBuscarMousePressed

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        btnBuscar.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setBackground(new Color(82,120,206));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseEntered
        btnActualizar.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_btnActualizarMouseEntered

    private void btnActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseExited
        btnActualizar.setBackground(new Color(82,120,206));
    }//GEN-LAST:event_btnActualizarMouseExited

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
frmPublicar pub = new frmPublicar();
        pub.setVisible(true);

    }//GEN-LAST:event_btnEntrarMouseClicked

    private void btnEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseEntered
        btnPublicar.setBackground(new Color(62,143,80));
    }//GEN-LAST:event_btnEntrarMouseEntered

    private void btnEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseExited
        btnPublicar.setBackground(new Color(82,120,206));
    }//GEN-LAST:event_btnEntrarMouseExited

    private void btnPublicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPublicarMouseClicked
        
    }//GEN-LAST:event_btnPublicarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JPanel Close;
    private javax.swing.JLabel EnQueEstasPensando;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Lupa;
    private javax.swing.JPanel PanelCrearPublicacion;
    private javax.swing.JPanel PerfilUsuario;
    private javax.swing.JPanel Recomendados;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JLabel Separador;
    private javax.swing.JPanel Tamaño;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnActualizar;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JLabel btnEntrar;
    private Clases.PanelRound btnPublicar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFotoPerfil;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
