/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;

/**
 *
 * @author joser
 */
public class frmPreguntaSalir extends javax.swing.JFrame {

    /**
     * Creates new form frmPreguntaSalir
     */
    int xMouse,yMouse;
    public frmPreguntaSalir() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlArrastrable = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRechazar = new javax.swing.JPanel();
        btnNo = new javax.swing.JLabel();
        btnAceptar1 = new javax.swing.JPanel();
        btnEntrar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlPrincipal.setBackground(new java.awt.Color(244, 244, 244));
        pnlPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlArrastrable.setBackground(new java.awt.Color(244, 244, 244));
        pnlArrastrable.setOpaque(false);
        pnlArrastrable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlArrastrableMouseDragged(evt);
            }
        });
        pnlArrastrable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlArrastrableMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlArrastrableLayout = new javax.swing.GroupLayout(pnlArrastrable);
        pnlArrastrable.setLayout(pnlArrastrableLayout);
        pnlArrastrableLayout.setHorizontalGroup(
            pnlArrastrableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pnlArrastrableLayout.setVerticalGroup(
            pnlArrastrableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlArrastrable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("¿Segur@ que deseas salir?");
        pnlPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        btnRechazar.setBackground(new java.awt.Color(82, 120, 206));

        btnNo.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnNo.setForeground(new java.awt.Color(255, 255, 255));
        btnNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNo.setText("No");
        btnNo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRechazarLayout = new javax.swing.GroupLayout(btnRechazar);
        btnRechazar.setLayout(btnRechazarLayout);
        btnRechazarLayout.setHorizontalGroup(
            btnRechazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRechazarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnRechazarLayout.setVerticalGroup(
            btnRechazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRechazarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlPrincipal.add(btnRechazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 110, 20));

        btnAceptar1.setBackground(new java.awt.Color(82, 120, 206));

        btnEntrar1.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnEntrar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEntrar1.setText("Si");
        btnEntrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEntrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntrar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntrar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAceptar1Layout = new javax.swing.GroupLayout(btnAceptar1);
        btnAceptar1.setLayout(btnAceptar1Layout);
        btnAceptar1Layout.setHorizontalGroup(
            btnAceptar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAceptar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEntrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAceptar1Layout.setVerticalGroup(
            btnAceptar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAceptar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEntrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlPrincipal.add(btnAceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 110, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlArrastrableMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlArrastrableMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_pnlArrastrableMouseDragged

    private void pnlArrastrableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlArrastrableMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlArrastrableMousePressed

    private void btnNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnNoMouseClicked

    private void btnNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoMouseEntered
        btnRechazar.setBackground(new Color(62,143,80));
    }//GEN-LAST:event_btnNoMouseEntered

    private void btnNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoMouseExited
        btnRechazar.setBackground(new Color(82,120,206));
    }//GEN-LAST:event_btnNoMouseExited

    private void btnEntrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrar1MouseClicked
        frmCerrar close = new frmCerrar();
        this.dispose();
        close.setVisible(true);
    }//GEN-LAST:event_btnEntrar1MouseClicked

    private void btnEntrar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrar1MouseEntered
        btnAceptar1.setBackground(new Color(255, 51, 0));
    }//GEN-LAST:event_btnEntrar1MouseEntered

    private void btnEntrar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrar1MouseExited
        btnAceptar1.setBackground(new Color(82,120,206));
    }//GEN-LAST:event_btnEntrar1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPreguntaSalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPreguntaSalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPreguntaSalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPreguntaSalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPreguntaSalir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAceptar1;
    private javax.swing.JLabel btnEntrar1;
    private javax.swing.JLabel btnNo;
    private javax.swing.JPanel btnRechazar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlArrastrable;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
