/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author joser
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    
    int xMouse, yMouse;
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
         Image icon = new ImageIcon(getClass().getResource("/img/soloLogo.png")).getImage();
       this.setIconImage(icon); 
    }
    
     private void InitContent(){
    ShowJPanel(new frmPerfil());
    }
    
    private void ShowJPanel(JPanel p){
    p.setSize(1038, 723);
    p.setLocation(0,0);
    
        pnlPrincipal.removeAll();
        pnlPrincipal.add(p, BorderLayout.CENTER);
        pnlPrincipal.revalidate();
        pnlPrincipal.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Close = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tamaño = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Barra = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JPanel();
        Lupa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PerfilUsuario = new javax.swing.JPanel();
        Separador = new javax.swing.JLabel();
        lblFotoPerfil = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Recomendados = new javax.swing.JPanel();
        UsuariosFakeVerso = new javax.swing.JLabel();
        PerfilUno = new javax.swing.JPanel();
        FotoPerfilUno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PerfilTres = new javax.swing.JPanel();
        FotoPerfilTres = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PerfilCuatro = new javax.swing.JPanel();
        FotoPerfilCuatro = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PerfilDos = new javax.swing.JPanel();
        FotoPerfilDos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PanelCrearPublicacion = new javax.swing.JPanel();
        EnQueEstasPensando = new javax.swing.JLabel();
        btnPublicar = new javax.swing.JPanel();
        btnEntrar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1046, 609));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setBackground(new java.awt.Color(82, 120, 206));
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CloseMouseReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");

        javax.swing.GroupLayout CloseLayout = new javax.swing.GroupLayout(Close);
        Close.setLayout(CloseLayout);
        CloseLayout.setHorizontalGroup(
            CloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CloseLayout.setVerticalGroup(
            CloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CloseLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        bg.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 30, 30));

        Tamaño.setBackground(new java.awt.Color(82, 120, 206));
        Tamaño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TamañoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TamañoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TamañoMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("_");

        javax.swing.GroupLayout TamañoLayout = new javax.swing.GroupLayout(Tamaño);
        Tamaño.setLayout(TamañoLayout);
        TamañoLayout.setHorizontalGroup(
            TamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TamañoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
        );
        TamañoLayout.setVerticalGroup(
            TamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TamañoLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        bg.add(Tamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 30, 30));

        btnActualizar.setBackground(new java.awt.Color(82, 120, 206));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMouseExited(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N

        javax.swing.GroupLayout btnActualizarLayout = new javax.swing.GroupLayout(btnActualizar);
        btnActualizar.setLayout(btnActualizarLayout);
        btnActualizarLayout.setHorizontalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        btnActualizarLayout.setVerticalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnActualizarLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 30, 30));

        Barra.setBackground(new java.awt.Color(82, 120, 206));
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });
        Barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chiquito.png"))); // NOI18N
        Barra.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 39));

        txtBuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscar.setText("Buscar");
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarMousePressed(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        Barra.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 0, 236, 30));

        btnBuscar.setBackground(new java.awt.Color(82, 120, 206));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        Lupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa (1).png"))); // NOI18N

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addComponent(Lupa)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(Lupa))
        );

        Barra.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 0, 30, 28));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoBarra.png"))); // NOI18N
        Barra.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 140, -1));

        bg.add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 30));

        Separador.setText("________________________________________________");

        lblFotoPerfil.setText("Foto perfil");
        lblFotoPerfil.setToolTipText("");
        lblFotoPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("Correo:");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setText("Telefono:");

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setText("Ciudad:");

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setText("Asiste a:");

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel17.setText("eric jasiel carballo.");

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel18.setText("ericjasiel20@gmail.com");

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel19.setText("+52 6421474302");

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel20.setText("Navojoa.");

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel21.setText("ITSON Navojoa.");

        javax.swing.GroupLayout PerfilUsuarioLayout = new javax.swing.GroupLayout(PerfilUsuario);
        PerfilUsuario.setLayout(PerfilUsuarioLayout);
        PerfilUsuarioLayout.setHorizontalGroup(
            PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerfilUsuarioLayout.createSequentialGroup()
                .addComponent(Separador)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(PerfilUsuarioLayout.createSequentialGroup()
                .addGroup(PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PerfilUsuarioLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(lblFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PerfilUsuarioLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PerfilUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PerfilUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PerfilUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PerfilUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PerfilUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PerfilUsuarioLayout.setVerticalGroup(
            PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerfilUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(Separador))
        );

        bg.add(PerfilUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 290, 360));

        Recomendados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsuariosFakeVerso.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        UsuariosFakeVerso.setText("Usuarios en el FakeVerso:");
        Recomendados.add(UsuariosFakeVerso, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 11, 190, -1));

        PerfilUno.setBackground(new java.awt.Color(225, 225, 225));
        PerfilUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PerfilUno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PerfilUnoMouseClicked(evt);
            }
        });

        FotoPerfilUno.setText("Foto perfil");
        FotoPerfilUno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout PerfilUnoLayout = new javax.swing.GroupLayout(PerfilUno);
        PerfilUno.setLayout(PerfilUnoLayout);
        PerfilUnoLayout.setHorizontalGroup(
            PerfilUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerfilUnoLayout.createSequentialGroup()
                .addComponent(FotoPerfilUno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addGap(0, 86, Short.MAX_VALUE))
        );
        PerfilUnoLayout.setVerticalGroup(
            PerfilUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerfilUnoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PerfilUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FotoPerfilUno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)))
        );

        Recomendados.add(PerfilUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 240, 70));

        PerfilTres.setBackground(new java.awt.Color(225, 225, 225));
        PerfilTres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        FotoPerfilTres.setText("Foto perfil");
        FotoPerfilTres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout PerfilTresLayout = new javax.swing.GroupLayout(PerfilTres);
        PerfilTres.setLayout(PerfilTresLayout);
        PerfilTresLayout.setHorizontalGroup(
            PerfilTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerfilTresLayout.createSequentialGroup()
                .addComponent(FotoPerfilTres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel10)
                .addGap(0, 88, Short.MAX_VALUE))
        );
        PerfilTresLayout.setVerticalGroup(
            PerfilTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerfilTresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PerfilTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FotoPerfilTres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)))
        );

        Recomendados.add(PerfilTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 240, 70));

        PerfilCuatro.setBackground(new java.awt.Color(225, 225, 225));
        PerfilCuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        FotoPerfilCuatro.setText("Foto perfil");
        FotoPerfilCuatro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout PerfilCuatroLayout = new javax.swing.GroupLayout(PerfilCuatro);
        PerfilCuatro.setLayout(PerfilCuatroLayout);
        PerfilCuatroLayout.setHorizontalGroup(
            PerfilCuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerfilCuatroLayout.createSequentialGroup()
                .addComponent(FotoPerfilCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel11)
                .addGap(0, 87, Short.MAX_VALUE))
        );
        PerfilCuatroLayout.setVerticalGroup(
            PerfilCuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerfilCuatroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PerfilCuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FotoPerfilCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)))
        );

        Recomendados.add(PerfilCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 70));

        PerfilDos.setBackground(new java.awt.Color(225, 225, 225));
        PerfilDos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        FotoPerfilDos.setText("Foto perfil");
        FotoPerfilDos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout PerfilDosLayout = new javax.swing.GroupLayout(PerfilDos);
        PerfilDos.setLayout(PerfilDosLayout);
        PerfilDosLayout.setHorizontalGroup(
            PerfilDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerfilDosLayout.createSequentialGroup()
                .addComponent(FotoPerfilDos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel9)
                .addGap(0, 90, Short.MAX_VALUE))
        );
        PerfilDosLayout.setVerticalGroup(
            PerfilDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerfilDosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PerfilDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FotoPerfilDos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)))
        );

        Recomendados.add(PerfilDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, 70));

        bg.add(Recomendados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 290, 380));

        PanelCrearPublicacion.setBackground(new java.awt.Color(255, 255, 255));
        PanelCrearPublicacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EnQueEstasPensando.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        EnQueEstasPensando.setText("¿En que estas pensando?");
        PanelCrearPublicacion.add(EnQueEstasPensando, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 12, 170, -1));

        btnPublicar.setBackground(new java.awt.Color(82, 120, 206));

        btnEntrar.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEntrar.setText("Publicar");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnPublicarLayout = new javax.swing.GroupLayout(btnPublicar);
        btnPublicar.setLayout(btnPublicarLayout);
        btnPublicarLayout.setHorizontalGroup(
            btnPublicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(btnPublicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnPublicarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnPublicarLayout.setVerticalGroup(
            btnPublicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(btnPublicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnPublicarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelCrearPublicacion.add(btnPublicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 170, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emojis.png"))); // NOI18N
        PanelCrearPublicacion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 310, 40));

        bg.add(PanelCrearPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 940, 40));

        jScrollPane1.setHorizontalScrollBar(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(753, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnlPrincipal);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 72, 940, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BarraMousePressed

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y- yMouse);
    }//GEN-LAST:event_BarraMouseDragged

    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        Close.setBackground(new Color(255, 51, 0));
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        Close.setBackground(new Color(82,120,206));
    }//GEN-LAST:event_CloseMouseExited

    private void CloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseReleased
        
    }//GEN-LAST:event_CloseMouseReleased

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        frmPreguntaSalir pr = new frmPreguntaSalir();
        pr.setVisible(true);
    }//GEN-LAST:event_CloseMouseClicked

    private void TamañoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TamañoMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_TamañoMouseClicked

    private void TamañoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TamañoMouseEntered
        Tamaño.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_TamañoMouseEntered

    private void TamañoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TamañoMouseExited
        Tamaño.setBackground(new Color(82,120,206));
    }//GEN-LAST:event_TamañoMouseExited

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMousePressed
        if (txtBuscar.getText().equals("Buscar")) {
            txtBuscar.setText("");
        txtBuscar.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_txtBuscarMousePressed

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        btnBuscar.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setBackground(new Color(82,120,206));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseEntered
        btnActualizar.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_btnActualizarMouseEntered

    private void btnActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseExited
        btnActualizar.setBackground(new Color(82,120,206));
    }//GEN-LAST:event_btnActualizarMouseExited

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
frmPublicar pub = new frmPublicar();
        pub.setVisible(true);

    }//GEN-LAST:event_btnEntrarMouseClicked

    private void btnEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseEntered
        btnPublicar.setBackground(new Color(62,143,80));
    }//GEN-LAST:event_btnEntrarMouseEntered

    private void btnEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseExited
        btnPublicar.setBackground(new Color(82,120,206));
    }//GEN-LAST:event_btnEntrarMouseExited

    private void PerfilUnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerfilUnoMouseClicked
        ShowJPanel(new frmPerfil());
    }//GEN-LAST:event_PerfilUnoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JPanel Close;
    private javax.swing.JLabel EnQueEstasPensando;
    private javax.swing.JLabel FotoPerfilCuatro;
    private javax.swing.JLabel FotoPerfilDos;
    private javax.swing.JLabel FotoPerfilTres;
    private javax.swing.JLabel FotoPerfilUno;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Lupa;
    private javax.swing.JPanel PanelCrearPublicacion;
    private javax.swing.JPanel PerfilCuatro;
    private javax.swing.JPanel PerfilDos;
    private javax.swing.JPanel PerfilTres;
    private javax.swing.JPanel PerfilUno;
    private javax.swing.JPanel PerfilUsuario;
    private javax.swing.JPanel Recomendados;
    private javax.swing.JLabel Separador;
    private javax.swing.JPanel Tamaño;
    private javax.swing.JLabel UsuariosFakeVerso;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnActualizar;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JLabel btnEntrar;
    private javax.swing.JPanel btnPublicar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFotoPerfil;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
